/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tugas3;

/**
 *
 * @author Asus
 */
public class formktp2 extends javax.swing.JFrame {

    /**
     * Creates new form formktp2
     */
    public formktp2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jtengah = new javax.swing.JPanel();
        jhome = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jberita = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jform = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        LblNama = new javax.swing.JLabel();
        TfNama = new javax.swing.JTextField();
        LblTTL = new javax.swing.JLabel();
        TfTmpt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TfTl = new javax.swing.JTextField();
        LblJk = new javax.swing.JLabel();
        RbLk = new javax.swing.JRadioButton();
        RbPr = new javax.swing.JRadioButton();
        LblAlamat = new javax.swing.JLabel();
        TfAlamat = new javax.swing.JTextField();
        LblRt = new javax.swing.JLabel();
        TfRt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        TfRw = new javax.swing.JTextField();
        LblKel = new javax.swing.JLabel();
        TfKel = new javax.swing.JTextField();
        LblKec = new javax.swing.JLabel();
        TfKec = new javax.swing.JTextField();
        LblKota = new javax.swing.JLabel();
        TfKota = new javax.swing.JTextField();
        LblAgama = new javax.swing.JLabel();
        CbAgama = new javax.swing.JComboBox();
        LblStatus = new javax.swing.JLabel();
        CbStatus = new javax.swing.JComboBox();
        LblGoldar = new javax.swing.JLabel();
        CbGoldar = new javax.swing.JComboBox();
        LblPkrj = new javax.swing.JLabel();
        TfPkrj = new javax.swing.JTextField();
        LblKwrg = new javax.swing.JLabel();
        RbWna = new javax.swing.JRadioButton();
        RbWni = new javax.swing.JRadioButton();
        BtnReset = new javax.swing.JButton();
        BtnRegister = new javax.swing.JButton();
        BtnExit = new javax.swing.JButton();
        jproker = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jatas = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BtnHome = new javax.swing.JButton();
        BtnBerita = new javax.swing.JButton();
        BtnForm = new javax.swing.JButton();
        BtnProker = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbawah = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jkiri = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jkanan = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtengah.setBackground(new java.awt.Color(255, 255, 255));
        jtengah.setLayout(new java.awt.CardLayout());

        jhome.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setIcon(new javax.swing.ImageIcon("D:\\Materi Kuliah\\Semester 4\\Praktikum\\P.Visual\\ss\\11.PNG")); // NOI18N

        jLabel17.setIcon(new javax.swing.ImageIcon("D:\\Materi Kuliah\\Semester 4\\Praktikum\\P.Visual\\ss\\12.PNG")); // NOI18N

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tugas3/13.PNG"))); // NOI18N

        javax.swing.GroupLayout jhomeLayout = new javax.swing.GroupLayout(jhome);
        jhome.setLayout(jhomeLayout);
        jhomeLayout.setHorizontalGroup(
            jhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jhomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel21))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jhomeLayout.setVerticalGroup(
            jhomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jhomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jtengah.add(jhome, "card2");

        jberita.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tugas3/berita.PNG"))); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 51, 255));
        jLabel19.setText("BERITA");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("OPEN RECRUITMENT PETUGAS LAPANGAN SENSUS ");

        javax.swing.GroupLayout jberitaLayout = new javax.swing.GroupLayout(jberita);
        jberita.setLayout(jberitaLayout);
        jberitaLayout.setHorizontalGroup(
            jberitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jberitaLayout.createSequentialGroup()
                .addComponent(jLabel19)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jberitaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jberitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        jberitaLayout.setVerticalGroup(
            jberitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jberitaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18))
        );

        jtengah.add(jberita, "card3");

        jform.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("FORM PENDATAAN");

        LblNama.setText("Nama");

        LblTTL.setText("Tempat/Tanggal Lahir");

        jLabel14.setText("/");

        LblJk.setText("Jenis Kelamin");

        buttonGroup1.add(RbLk);
        RbLk.setText("Laki-laki");

        buttonGroup1.add(RbPr);
        RbPr.setText("Perempuan");

        LblAlamat.setText("Alamat");

        LblRt.setText("RT/RW");

        jLabel15.setText("/");

        LblKel.setText("Kel/Desa");

        LblKec.setText("Kecamatan");

        LblKota.setText("Kota");

        LblAgama.setText("Agama");

        CbAgama.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ISLAM", "KRISTEN", "BUDHA", "HINDU", "KONGHUCHU" }));
        CbAgama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CbAgamaMouseClicked(evt);
            }
        });

        LblStatus.setText("Status");

        CbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "KAWIN", "BELUM KAWIN" }));
        CbStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CbStatusMouseClicked(evt);
            }
        });

        LblGoldar.setText("Golongan Darah");

        CbGoldar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "O", "AB" }));
        CbGoldar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CbGoldarMouseClicked(evt);
            }
        });

        LblPkrj.setText("Pekerjaan");

        LblKwrg.setText("Kewarganegaraan");

        buttonGroup2.add(RbWna);
        RbWna.setText("WNA");

        buttonGroup2.add(RbWni);
        RbWni.setText("WNI");

        BtnReset.setText("RESET");
        BtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResetActionPerformed(evt);
            }
        });

        BtnRegister.setText("REGISTER");
        BtnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegisterActionPerformed(evt);
            }
        });

        BtnExit.setText("EXIT");
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jformLayout = new javax.swing.GroupLayout(jform);
        jform.setLayout(jformLayout);
        jformLayout.setHorizontalGroup(
            jformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jformLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblNama)
                    .addComponent(LblTTL)
                    .addComponent(LblAlamat)
                    .addComponent(LblJk)
                    .addGroup(jformLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblKota)
                            .addComponent(LblKec)
                            .addComponent(LblKel)
                            .addComponent(LblRt)))
                    .addComponent(LblAgama)
                    .addComponent(LblStatus)
                    .addComponent(LblGoldar)
                    .addComponent(LblPkrj)
                    .addComponent(LblKwrg))
                .addGap(19, 19, 19)
                .addGroup(jformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jformLayout.createSequentialGroup()
                        .addComponent(RbWna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RbWni))
                    .addGroup(jformLayout.createSequentialGroup()
                        .addGroup(jformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(CbGoldar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CbStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CbAgama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jformLayout.createSequentialGroup()
                                .addComponent(RbLk)
                                .addGap(18, 18, 18)
                                .addComponent(RbPr))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jformLayout.createSequentialGroup()
                                .addComponent(TfTmpt, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TfTl))
                            .addComponent(TfAlamat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jformLayout.createSequentialGroup()
                                .addComponent(TfRt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TfRw, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TfKel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TfKec, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TfKota, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TfPkrj, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TfNama, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(41, 41, 41)
                        .addGroup(jformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnReset)
                            .addComponent(BtnRegister)
                            .addComponent(BtnExit))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jformLayout.setVerticalGroup(
            jformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jformLayout.createSequentialGroup()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblNama)
                    .addComponent(TfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblTTL)
                    .addComponent(TfTmpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(TfTl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblJk)
                    .addComponent(RbLk)
                    .addComponent(RbPr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblAlamat)
                    .addComponent(BtnReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfRt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(TfRw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblRt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfKel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblKel)
                    .addComponent(BtnRegister))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblKec)
                    .addComponent(TfKec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblKota)
                    .addGroup(jformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TfKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtnExit)))
                .addGap(18, 18, 18)
                .addGroup(jformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblAgama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbGoldar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblGoldar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfPkrj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblPkrj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblKwrg)
                    .addGroup(jformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RbWna)
                        .addComponent(RbWni)))
                .addGap(0, 85, Short.MAX_VALUE))
        );

        jtengah.add(jform, "card5");

        jproker.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 51, 204));
        jLabel22.setText("INFORMASI UMUM");

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tugas3/23.PNG"))); // NOI18N

        javax.swing.GroupLayout jprokerLayout = new javax.swing.GroupLayout(jproker);
        jproker.setLayout(jprokerLayout);
        jprokerLayout.setHorizontalGroup(
            jprokerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jprokerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jprokerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jprokerLayout.setVerticalGroup(
            jprokerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jprokerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addContainerGap(434, Short.MAX_VALUE))
        );

        jtengah.add(jproker, "card4");

        getContentPane().add(jtengah, java.awt.BorderLayout.CENTER);

        jatas.setBackground(new java.awt.Color(0, 102, 204));

        jPanel2.setBackground(new java.awt.Color(0, 51, 153));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        BtnHome.setText("Home");
        BtnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHomeActionPerformed(evt);
            }
        });
        jPanel2.add(BtnHome);

        BtnBerita.setText("Berita");
        BtnBerita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBeritaActionPerformed(evt);
            }
        });
        jPanel2.add(BtnBerita);

        BtnForm.setText("Form Pendataan");
        BtnForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFormActionPerformed(evt);
            }
        });
        jPanel2.add(BtnForm);

        BtnProker.setText("Proker");
        BtnProker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProkerActionPerformed(evt);
            }
        });
        jPanel2.add(BtnProker);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PENDATAAN PENDUDUK ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BADAN PUSAT STATISTIK KOTA SAMARINDA");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("2016");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tugas3/bps.PNG"))); // NOI18N

        javax.swing.GroupLayout jatasLayout = new javax.swing.GroupLayout(jatas);
        jatas.setLayout(jatasLayout);
        jatasLayout.setHorizontalGroup(
            jatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jatasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(414, Short.MAX_VALUE))
        );
        jatasLayout.setVerticalGroup(
            jatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jatasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jatasLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addComponent(jLabel4))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jatas, java.awt.BorderLayout.PAGE_START);

        jbawah.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setText("Badan Pusat Statistik Kota Samarinda (Statistics Samarinda)");

        jLabel10.setText("Jl. KH. Achmad Dahlan No. 33 Samarinda 75117, Telp. 0541-743661 Fax 0541-735762 E-mail:bps6472@bps.go.id");

        jLabel11.setText("Hak Cipta © 2017 Badan Pusat Statistik");

        jLabel12.setText("Semua Hak Dilindungi");

        javax.swing.GroupLayout jbawahLayout = new javax.swing.GroupLayout(jbawah);
        jbawah.setLayout(jbawahLayout);
        jbawahLayout.setHorizontalGroup(
            jbawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbawahLayout.createSequentialGroup()
                .addGroup(jbawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jbawahLayout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(jLabel9))
                    .addGroup(jbawahLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel10))
                    .addGroup(jbawahLayout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(jLabel11))
                    .addGroup(jbawahLayout.createSequentialGroup()
                        .addGap(395, 395, 395)
                        .addComponent(jLabel12)))
                .addContainerGap(327, Short.MAX_VALUE))
        );
        jbawahLayout.setVerticalGroup(
            jbawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbawahLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jbawah, java.awt.BorderLayout.PAGE_END);

        jkiri.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tugas3/kanan3.PNG"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\Materi Kuliah\\Semester 4\\Praktikum\\P.Visual\\ss\\kanan2.PNG")); // NOI18N

        javax.swing.GroupLayout jkiriLayout = new javax.swing.GroupLayout(jkiri);
        jkiri.setLayout(jkiriLayout);
        jkiriLayout.setHorizontalGroup(
            jkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jkiriLayout.createSequentialGroup()
                .addGroup(jkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jkiriLayout.setVerticalGroup(
            jkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jkiriLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(0, 169, Short.MAX_VALUE))
        );

        getContentPane().add(jkiri, java.awt.BorderLayout.LINE_END);

        jkanan.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tugas3/kiri2.PNG"))); // NOI18N
        jLabel6.setText("jLabel6");

        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\Materi Kuliah\\Semester 4\\Praktikum\\P.Visual\\ss\\kiri3.PNG")); // NOI18N

        javax.swing.GroupLayout jkananLayout = new javax.swing.GroupLayout(jkanan);
        jkanan.setLayout(jkananLayout);
        jkananLayout.setHorizontalGroup(
            jkananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jkananLayout.createSequentialGroup()
                .addGroup(jkananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        jkananLayout.setVerticalGroup(
            jkananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jkananLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(0, 215, Short.MAX_VALUE))
        );

        getContentPane().add(jkanan, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHomeActionPerformed
        // TODO add your handling code here:
    jhome.setVisible(true);//pengaturan dimana jhome bernilai true yang berarti akan tampil dalam aksi ini
    jberita.setVisible(false);//pengaturan dimana jberita bernilai false yang berarti tidak akan tampil dalam aksi ini
    jform.setVisible(false);//pengaturan dimana jform bernilai false yang berarti tidak akan tampil dalam aksi ini
    jproker.setVisible(false);//pengaturan dimana jproker bernilai false yang berarti tidak akan tampil dalam aksi ini
    }//GEN-LAST:event_BtnHomeActionPerformed

    private void CbAgamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CbAgamaMouseClicked
        // TODO add your handling code here:
        CbAgama.getSelectedItem();//getSelectedItem berarti mengambil item yang telah terpilih sebagai agama
    }//GEN-LAST:event_CbAgamaMouseClicked

    private void CbStatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CbStatusMouseClicked
        // TODO add your handling code here:
        CbStatus.getSelectedItem();//getSelectedItem berarti mengambil item yang telah terpilih sebagai status
    }//GEN-LAST:event_CbStatusMouseClicked

    private void CbGoldarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CbGoldarMouseClicked
        // TODO add your handling code here:
        CbGoldar.getSelectedItem();//getSelectedItem berarti mengambil item yang telah terpilih sebagai golongan darah
    }//GEN-LAST:event_CbGoldarMouseClicked

    private void BtnProkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProkerActionPerformed
        // TODO add your handling code here:
    jhome.setVisible(false);//pengaturan dimana jhome bernilai false yang berarti tidak akan tampil dalam aksi ini
    jberita.setVisible(false);//pengaturan dimana jberita bernilai false yang berarti tidak akan tampil dalam aksi ini
    jform.setVisible(false);//pengaturan dimana jform bernilai false yang berarti tidak akan tampil dalam aksi ini
    jproker.setVisible(true);//pengaturan dimana jproker bernilai true yang berarti akan tampil dalam aksi ini
    }//GEN-LAST:event_BtnProkerActionPerformed

    private void BtnFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFormActionPerformed
        // TODO add your handling code here:
    jhome.setVisible(false);//pengaturan dimana jhome bernilai false yang berarti tidak akan tampil dalam aksi ini
    jberita.setVisible(false);//pengaturan dimana jberita bernilai false yang berarti tidak akan tampil dalam aksi ini
    jform.setVisible(true);//pengaturan dimana jform bernilai true yang berarti akan tampil dalam aksi ini
    jproker.setVisible(false);//pengaturan dimana jproker bernilai false yang berarti tidak akan tampil dalam aksi ini
    }//GEN-LAST:event_BtnFormActionPerformed

    private void BtnBeritaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBeritaActionPerformed
        // TODO add your handling code here:
    jhome.setVisible(false);//pengaturan dimana jhome bernilai false yang berarti tidak akan tampil dalam aksi ini
    jberita.setVisible(true);//pengaturan dimana jberita bernilai true yang berarti akan tampil dalam aksi ini
    jform.setVisible(false);//pengaturan dimana jform bernilai false yang berarti tidak akan tampil dalam aksi ini
    jproker.setVisible(false);//pengaturan dimana jproker bernilai false yang berarti tidak akan tampil dalam aksi ini
    }//GEN-LAST:event_BtnBeritaActionPerformed

    private void BtnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegisterActionPerformed
        // TODO add your handling code here:
    String Nama, TTL1, TTL2, JK=null, Alamat, RT, RW, Kel, Kec, Kota, Agama, Status, Goldar, Pkrj; //ini adalah pendeklarasian variabel yang akan dipakai dimana bertipe string
    Nama = TfNama.getText();//fungsi untuk mendapatkan inputan yg diisi di TfNama yg akan disimpan sebagai Nama
    TTL1 = TfTmpt.getText();//fungsi untuk mendapatkan inputan yg diisi di TfTmpt yg akan disimpan sebagai TTL1
    TTL2 = TfTl.getText();//fungsi untuk mendapatkan inputan yg diisi di TfTl yg akan disimpan sebagai TTL2
        if (RbLk.isSelected())//pegkondisian dimana jika RbLk yang terpilih
        {JK = RbLk.getText();}//maka RbLk yang akan diambil dan tampil sebagai Jenis Kelamin
        else if (RbPr.isSelected())//tetapi jika RbLk tidak dipilih dan RbPr yang terpilih
        {JK = RbPr.getText();}//maka RbPr yang akan diambil dan tampil sebagai Jenis Kelamin
    Alamat = TfAlamat.getText();//fungsi untuk mendapatkan inputan yg diisi di TfAlamat yg akan disimpan sebagai Alamat
    RT = TfRt.getText();//fungsi untuk mendapatkan inputan yg diisi di TfRt yg akan disimpan sebagai RT
    RW = TfRw.getText();//fungsi untuk mendapatkan inputan yg diisi di TfRw yg akan disimpan sebagai RW
    Kel = TfKel.getText();//fungsi untuk mendapatkan inputan yg diisi di TfKel yg akan disimpan sebagai Kelurahan
    Kec = TfKec.getText();//fungsi untuk mendapatkan inputan yg diisi di TfKec yg akan disimpan sebagai Kecamatan
    Kota = TfKota.getText();//fungsi untuk mendapatkan inputan yg diisi di TfKota yg akan disimpan sebagai Kota
    Agama = CbAgama.getSelectedItem().toString();//pengkondisian dimana Agama yg terpilih dalam CbAgama akan di ambil dan ditampilkan sebagai Agama 
    Status = CbStatus.getSelectedItem().toString();//pengkondisian dimana Status yg terpilih dalam CbStatus akan di ambil dan ditampilkan sebagai Status
    Goldar = CbGoldar.getSelectedItem().toString();//pengkondisian dimana Golongan Darah yg terpilih dalam CbGoldar akan di ambil dan ditampilkan sebagai Golongan Darah
    Pkrj = TfPkrj.getText();//fungsi untuk mendapatkan inputan yg diisi di TfPkrj yg akan disimpan sebagai Pekerjaan
    String Kwrg=null;
        if (RbWna.isSelected())//pegkondisian dimana jika RbWna yang terpilih
        {Kwrg = RbWna.getText();}//maka RbWna yang akan diambil dan tampil sebagai Kewarganegaraan
        else if (RbWni.isSelected())//tetapi jika RbWna tidak dipilih dan RbWni yang terpilih
        {Kwrg = RbWni.getText();}//maka RbWni yang akan diambil dan tampil sebagai Kewarganegaraan
        
    outktp x=new outktp(Nama, TTL1, TTL2, JK, Alamat, RT, RW, Kel, Kec, Kota, Agama, Status, Goldar, Pkrj, Kwrg);//pembuatan objek untuk outktp sebagai outputan dari proses inputan di atas
    x.setVisible(true);//mengatur inputan yang telah diinput bernilai true yang berarti bernilai benar dan akan tampil sebagai outputan
    }//GEN-LAST:event_BtnRegisterActionPerformed

    private void BtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResetActionPerformed
        // TODO add your handling code here:
    TfNama.setText("");//mengatur TfNama kosong
    TfTmpt.setText("");//mengatur TfTmpt kosong
    TfTl.setText("");//mengatur TfTl kosong
    buttonGroup1.clearSelection();//menghapus pilihan buttonGroup1 yaitu Jenis Kelamin agar kosong
    TfAlamat.setText("");//mengatur TfAlamat kosong
    TfRt.setText("");//mengatur TfRt kosong
    TfRw.setText("");//mengatur TfRw kosong
    TfKel.setText("");//mengatur TfKel kosong
    TfKec.setText("");//mengatur TfKec kosong
    TfKota.setText("");//mengatur TfKota kosong
    TfPkrj.setText("");//mengatur TfPkrj kosong
    buttonGroup2.clearSelection();//menghapus pilihan buttonGroup2 yaitu Kewarganegaraan agar kosong
    CbAgama.setSelectedItem(null);//mengatur pilihan CbAgama agar bernilai null atau kosong
    CbStatus.setSelectedItem(null);//mengatur pilihan CbStatus agar bernilai null atau kosong
    CbGoldar.setSelectedItem(null);//mengatur pilihan CbGoldar agar bernilai null atau kosong
    }//GEN-LAST:event_BtnResetActionPerformed

    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
        // TODO add your handling code here:
    this.dispose();//fungsi agar button ini sebagai tombol untuk menutup
    }//GEN-LAST:event_BtnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formktp2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formktp2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formktp2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formktp2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formktp2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBerita;
    private javax.swing.JButton BtnExit;
    private javax.swing.JButton BtnForm;
    private javax.swing.JButton BtnHome;
    private javax.swing.JButton BtnProker;
    private javax.swing.JButton BtnRegister;
    private javax.swing.JButton BtnReset;
    private javax.swing.JComboBox CbAgama;
    private javax.swing.JComboBox CbGoldar;
    private javax.swing.JComboBox CbStatus;
    private javax.swing.JLabel LblAgama;
    private javax.swing.JLabel LblAlamat;
    private javax.swing.JLabel LblGoldar;
    private javax.swing.JLabel LblJk;
    private javax.swing.JLabel LblKec;
    private javax.swing.JLabel LblKel;
    private javax.swing.JLabel LblKota;
    private javax.swing.JLabel LblKwrg;
    private javax.swing.JLabel LblNama;
    private javax.swing.JLabel LblPkrj;
    private javax.swing.JLabel LblRt;
    private javax.swing.JLabel LblStatus;
    private javax.swing.JLabel LblTTL;
    private javax.swing.JRadioButton RbLk;
    private javax.swing.JRadioButton RbPr;
    private javax.swing.JRadioButton RbWna;
    private javax.swing.JRadioButton RbWni;
    private javax.swing.JTextField TfAlamat;
    private javax.swing.JTextField TfKec;
    private javax.swing.JTextField TfKel;
    private javax.swing.JTextField TfKota;
    private javax.swing.JTextField TfNama;
    private javax.swing.JTextField TfPkrj;
    private javax.swing.JTextField TfRt;
    private javax.swing.JTextField TfRw;
    private javax.swing.JTextField TfTl;
    private javax.swing.JTextField TfTmpt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jatas;
    private javax.swing.JPanel jbawah;
    private javax.swing.JPanel jberita;
    private javax.swing.JPanel jform;
    private javax.swing.JPanel jhome;
    private javax.swing.JPanel jkanan;
    private javax.swing.JPanel jkiri;
    private javax.swing.JPanel jproker;
    private javax.swing.JPanel jtengah;
    // End of variables declaration//GEN-END:variables
}
