package Tugas3;

import Tugas2.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class outktp extends javax.swing.JFrame {

    /**
     * Creates new form outputktp
     */
    public outktp() {
        initComponents();
    }
    public outktp(String Nama, String TTL1, String TTL2, String JK, String Alamat, String RT, String RW,String Kel, String Kec, String Kota, String Agama, String Status, String Goldar, String Pkrj, String Kwrg) {//pendeklarasian variabel yang digunakan
        initComponents();
        jNama.setText(Nama);//mengatur Nama yang telah diinputkan di form inputktp kedalam jNama
        jTTL1.setText(TTL1);//mengatur TTL1 yang telah diinputkan di form inputktp kedalam jTTL1
        jTTL2.setText(TTL2);//mengatur TTL2 yang telah diinputkan di form inputktp kedalam jTTL2
        jJK.setText(""+JK);//mengatur JK yang telah diinputkan di form inputktp kedalam jJK
        jAlamat.setText(Alamat);//mengatur Alamat yang telah diinputkan di form inputktp kedalam jAlamat
        jRt.setText(RT);//mengatur RT yang telah diinputkan di form inputktp kedalam jRt
        jRw.setText(RW);//mengatur RW yang telah diinputkan di form inputktp kedalam jRw
        jKel.setText(Kel);//mengatur Kelurahan yang telah diinputkan di form inputktp kedalam jKel
        jKec.setText(Kec);//mengatur Kecamatan yang telah diinputkan di form inputktp kedalam jKec
        jKota.setText(Kota);//mengatur Kota yang telah diinputkan di form inputktp kedalam jKota
        jAgama.setText(""+Agama);//mengatur Agama yang telah diinputkan di form inputktp kedalam jAgama
        jStatus.setText(""+Status);//mengatur Status yang telah diinputkan di form inputktp kedalam jStatus
        jGoldar.setText(""+Goldar);//mengatur Golongan Darah yang telah diinputkan di form inputktp kedalam jGoldar
        jPkrj.setText(Pkrj);//mengatur Pekerjaan yang telah diinputkan di form inputktp kedalam jPkrj
        jKwrg.setText(""+Kwrg);//mengatur Kewarganegaraan yang telah diinputkan di form inputktp kedalam jKwrg
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LblNama = new javax.swing.JLabel();
        LblTTL = new javax.swing.JLabel();
        LblJk = new javax.swing.JLabel();
        LblGoldar = new javax.swing.JLabel();
        LblAlamat = new javax.swing.JLabel();
        LblRt = new javax.swing.JLabel();
        LblKel = new javax.swing.JLabel();
        LblKec = new javax.swing.JLabel();
        LblKota = new javax.swing.JLabel();
        LblAgama = new javax.swing.JLabel();
        LblStatus = new javax.swing.JLabel();
        LblPkrj = new javax.swing.JLabel();
        LblKwrg = new javax.swing.JLabel();
        jNama = new javax.swing.JLabel();
        jTTL1 = new javax.swing.JLabel();
        jTTL2 = new javax.swing.JLabel();
        jJK = new javax.swing.JLabel();
        jGoldar = new javax.swing.JLabel();
        jAlamat = new javax.swing.JLabel();
        jRt = new javax.swing.JLabel();
        jRw = new javax.swing.JLabel();
        jKel = new javax.swing.JLabel();
        jKec = new javax.swing.JLabel();
        jKota = new javax.swing.JLabel();
        jAgama = new javax.swing.JLabel();
        jStatus = new javax.swing.JLabel();
        jPkrj = new javax.swing.JLabel();
        jKwrg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Kartu Tanda Penduduk (KTP)");

        LblNama.setText("Nama");

        LblTTL.setText("Tempat/Tanggal Lahir");

        LblJk.setText("Jenis Kelamin");

        LblGoldar.setText("Golongan Darah");

        LblAlamat.setText("Alamat");

        LblRt.setText("RT/RW");

        LblKel.setText("Kel/Desa");

        LblKec.setText("Kecamatan");

        LblKota.setText("Kota");

        LblAgama.setText("Agama");

        LblStatus.setText("Status");

        LblPkrj.setText("Pekerjaan");

        LblKwrg.setText("Kewarganegaraan");

        jNama.setText("jLabel2");

        jTTL1.setText("jLabel3");

        jTTL2.setText("jLabel4");

        jJK.setText("jLabel5");

        jGoldar.setText("jLabel6");

        jAlamat.setText("jLabel7");

        jRt.setText("jLabel8");

        jRw.setText("jLabel10");

        jKel.setText("jLabel11");

        jKec.setText("jLabel12");

        jKota.setText("jLabel13");

        jAgama.setText("jLabel14");

        jStatus.setText("jLabel15");

        jPkrj.setText("jLabel16");

        jKwrg.setText("jLabel17");

        jLabel2.setText("/");

        jLabel3.setText("/");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblNama)
                            .addComponent(LblTTL)
                            .addComponent(LblJk)
                            .addComponent(LblGoldar)
                            .addComponent(LblAlamat)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblKel)
                                    .addComponent(LblRt)
                                    .addComponent(LblKec)
                                    .addComponent(LblKota)))
                            .addComponent(LblAgama)
                            .addComponent(LblStatus)
                            .addComponent(LblPkrj)
                            .addComponent(LblKwrg))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jKwrg)
                            .addComponent(jPkrj)
                            .addComponent(jStatus)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRt)
                                .addGap(3, 3, 3)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRw))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTTL1)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTTL2))
                            .addComponent(jNama)
                            .addComponent(jJK)
                            .addComponent(jGoldar)
                            .addComponent(jAlamat)
                            .addComponent(jKel)
                            .addComponent(jKec)
                            .addComponent(jKota)
                            .addComponent(jAgama)))
                    .addComponent(jButton2))
                .addContainerGap(423, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblNama)
                    .addComponent(jNama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblTTL)
                    .addComponent(jTTL1)
                    .addComponent(jTTL2)
                    .addComponent(jLabel3))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblJk)
                    .addComponent(jJK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblGoldar)
                    .addComponent(jGoldar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblAlamat)
                    .addComponent(jAlamat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblRt)
                    .addComponent(jRt)
                    .addComponent(jRw)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblKel)
                    .addComponent(jKel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblKec)
                    .addComponent(jKec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblKota)
                    .addComponent(jKota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblAgama)
                    .addComponent(jAgama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblStatus)
                    .addComponent(jStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblPkrj)
                    .addComponent(jPkrj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblKwrg)
                    .addComponent(jKwrg))
                .addGap(29, 29, 29)
                .addComponent(jButton2)
                .addGap(0, 44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    this.dispose();//fungsi agar button ini sebagai tombol untuk menutup
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(outktp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(outktp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(outktp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(outktp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new outktp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblAgama;
    private javax.swing.JLabel LblAlamat;
    private javax.swing.JLabel LblGoldar;
    private javax.swing.JLabel LblJk;
    private javax.swing.JLabel LblKec;
    private javax.swing.JLabel LblKel;
    private javax.swing.JLabel LblKota;
    private javax.swing.JLabel LblKwrg;
    private javax.swing.JLabel LblNama;
    private javax.swing.JLabel LblPkrj;
    private javax.swing.JLabel LblRt;
    private javax.swing.JLabel LblStatus;
    private javax.swing.JLabel LblTTL;
    private javax.swing.JLabel jAgama;
    private javax.swing.JLabel jAlamat;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jGoldar;
    private javax.swing.JLabel jJK;
    private javax.swing.JLabel jKec;
    private javax.swing.JLabel jKel;
    private javax.swing.JLabel jKota;
    private javax.swing.JLabel jKwrg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jNama;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jPkrj;
    private javax.swing.JLabel jRt;
    private javax.swing.JLabel jRw;
    private javax.swing.JLabel jStatus;
    private javax.swing.JLabel jTTL1;
    private javax.swing.JLabel jTTL2;
    // End of variables declaration//GEN-END:variables
}
